name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Added"
    labels:
      - "enhancement"
  - title: "Changed"
    labels:
      - "technical dept / refactoring"
      - "Continuous Integration"
      - "documentation"
  - title: "Fixed"
    labels:
      - "bug"

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

exclude-labels:
  - "skip-changelog"
  - "nice to have"
  - "Pedantic"

template: |
  ## [Unreleased]

  $CHANGES
